main:
  - name: Home
    url: /
    weight: 1

  - name: About
    url: about/
    weight: 5

  - name: Blog
    url: blog/
    weight: 4

  - name: Trusted Profesional Directory
    url: directory/
    weight: 2

  - weight: 3
    name: Home Maintenance Library
    hasChildren: true
  
  - parent: Home Maintenance Library
    name: Understanding My House
    url: understanding/
  
  - parent: Home Maintenance Library
    name: Maintenance & Repairs
    url: maintenance/
  
  - parent: Home Maintenance Library
    name: Appliance Information & Manuals
    url: manuals/

footer:
  - name: About
    url: about/
    weight: 2
 
  - name: TREC Consumer Protection Notice
    url:  https://www.trec.texas.gov/sites/default/files/pdf-forms/CN%201-5_0.pdf
    weight: 1
