main:
  - name: Directory
    url: directory/
    weight: 1
    pin: true

  - name: Library
    url: library/
    weight: 2
    pin: true
  
  - name: Services
    weight: 3

  - name: Inspection Services
    url: services/
    parent: Services
    weight: 1

  - name: Service Area
    url: services/area
    parent: Services
    weight: 2

#- name: More
#  weight: 3


  #- name: Ryanade
  #  parent: More
  #  url: ryanade/

footer:
  - name: Credits
    url: credits/
    weight: 2
 
  - name: TREC Consumer Protection Notice
    url:  https://www.trec.texas.gov/sites/default/files/pdf-forms/CN%201-5_0.pdf
    weight: 1
