main:
  - name: Home
    url: /
    weight: 1

  - name: Trusted Profesional Directory
    url: directory/
    weight: 2

  - name: Library Of Information
    url: library/
    weight: 3

footer:
  - name: Credits
    url: credits/
    weight: 2
 
  - name: TREC Consumer Protection Notice
    url:  https://www.trec.texas.gov/sites/default/files/pdf-forms/CN%201-5_0.pdf
    weight: 1
