main:
  - name: Information
    weight: 1

  - name: Services
    weight: 2

  - name: Trusted Directory
    parent: Information
    url: directory/
    weight: 1

  - name: Information Library
    parent: Information
    url: library/
    weight: 2
  
  - name: Services & Pricing
    url: services/
    parent: Services
    weight: 1

  - name: Service Area
    url: area/
    parent: Services
    weight: 2

  - name: 360° Photo Gallery
    url: 360gallery/
    parent: Services
    weight: 3

#- name: More
#  weight: 3


  #- name: Ryanade
  #  parent: More
  #  url: ryanade/

footer:
  - name: Credits
    url: credits/
    weight: 2
 
  - name: TREC Consumer Protection Notice
    url:  https://www.trec.texas.gov/sites/default/files/pdf-forms/CN%201-5_0.pdf
    weight: 1
