main:
  - name: Directory
    url: directory/
    weight: 1

  - name: Library
    url: library/
    weight: 2

  - name: More
    weight: 3

  - name: Ryanade
    parent: More
    url: ryanade/

footer:
  - name: Credits
    url: credits/
    weight: 2
 
  - name: TREC Consumer Protection Notice
    url:  https://www.trec.texas.gov/sites/default/files/pdf-forms/CN%201-5_0.pdf
    weight: 1
